name: Build Docker Debian 11 image

on:
  workflow_dispatch:
  push:
    branches: main

env:
  IMAGE_ID: ghcr.io/${{ github.repository }}/debian-pdns-base
  IMAGE_TAG: "11"

jobs:
  login:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_ID:${{ github.run_number }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push into Github Container Registry
        run: |
          docker push $IMAGE_ID:${{ github.run_number }}
          docker tag $IMAGE_ID:${{ github.run_number }} $IMAGE_ID:$IMAGE_TAG
          docker push $IMAGE_ID:$IMAGE_TAG
