name: Build Docker Debian 11 image

on: [workflow_dispatch]
#   push:
#     branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}/debian-pdns-base:11

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push into Github Container Registry
        run: docker push ghcr.io/${{ github.repository }}/debian-pdns-base:11
